openapi: 3.0.3
info:
  title: PIND
  version: '0.1'
  description: PIND doc description
servers:
  - url: http://127.0.0.1:5000
    variables: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: faq
    description: everything related to FAQs
  - name: ticket
    description: everything about tickets
  - name: staff only
    description: actions that can only be performed by staff
  - name: user
    description: user registration and login
paths:
  /register:
    description: register new user
    post:
      tags:
        - user
      summary: ""
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: andrew@support.iitm.ac.in
                user_type:
                  type: string
                  example: staff
                password:
                  type: string
                  example: underwearsarethebest
              required:
                - email
                - password
                - user_type
      operationId: userGen
      responses:
        '200':
          description: User registered successfully  
        '401':
          description: Conflict
          content:
            application/json:
              examples:
                401 result:
                  value: account already exists with this email 
  /login:
    post:
      tags: 
        - user
      summary: ""
      description: Log in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: andrew@support.iitm.ac.in
                password:
                  type: string
                  example: pass1234
              required:
                - email
                - password
      operationId: userLogin
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: XcisyoBcluyhsBVLUKBVF
        '401':
          description: Invalid credentials
          content:
            application/json:
              examples:
                401 result:
                  value: email and password do not match
  /ticket:
    description: operations related to tickets
    post:
      summary: ''
      description: create a new ticket for a given user id (student only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  example: 2
                deets:
                  type: string
                  example: I am unable to access course XYZ
                date:
                  type: integer
                  example: 1231231
                categories:
                  type: array
                  items:
                    type: string
                  example:
                    - XYZ
                    - Operational
      operationId: ticket1
      responses:
        '201':
          description: sample success response - return newly created ticket
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: null
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    get:
      summary: ''
      description: get paginated tickets for a user
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            description: page number
            example: 1
             
        - in: query
          name: size
          schema: 
            type: integer
            description: maximum tickets in the response
            example: 2
            
      operationId: ticket2
      responses:
        '200':
          description: sample success response - return tickets
          content:
            application/json:
              examples:
                200 result:
                  value:
                    tickets: 
                      - {
                        ticketId: 3,
                        userId: 2,
                        deets: I am unable to  access course XYZ,
                        status: Open,
                        replies: [],
                        likes: 0,
                        categories: [XYZ, Operational],
                        linkedTicket: null,
                          
                      }
                      - {
                        ticketId: 4,
                        userId: 2,
                        deets: Regarding graded assignment,
                        status: Open,
                        replies: [],
                        likes: 2,
                        categories: [Graded],
                        linkedTicket: null,
                      }
                    
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: no tickets found

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    
  /ticket/{ticketId}:
    description: Specific ticket details
    get:
      summary: ''
      description: get ticket details by ticketId
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
        
      operationId: ticketB1
      responses:
        '200':
          description: sample success response - return ticket
          content:
            application/json:
              examples:
                200 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: null
                  
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: ticket not found

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      
      tags:
        - ticket
    put:
      summary: ''
      description: update a given ticket
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deets:
                  type: string
                  example: I am unable to access course XYZ since yesterday
                categories:
                  type: array
                  items:
                    type: string
                  example:
                    - XYZ2
                    - Operational
      operationId: ticketB2
      responses:
        '200':
          description: sample success response - return updated ticket
          content:
            application/json:
              examples:
                200 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ2 since yesterday
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ2
                      - Operational
                    linkedTicket: null
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: ticket not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    delete:
      summary: ''
      description: update a given ticket
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
      
      operationId: ticketB3
      responses:
        '200':
          description: sample success response - deleted successfully
          content:
            application/json:
              examples:
                200 result:
                  value:
                    status: true
                    message: deleted successfully
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                401 result:
                  value: ticket not found
                  
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
  /ticket/markDuplicate:
    description: operations related to tickets
    put:
      summary: ''
      description: create a new ticket for a given user id (student only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentTicketId:
                  type: integer
                  example: 3
                originalTicketId:
                  type: integer
                  example: 5
      operationId: ticketM1
      responses:
        '201':
          description: sample success response - return ticket marked duplicate
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Resolved
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: 5
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
  /ticket/reply:
    put:
      summary: ''
      description: reply to a ticket
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ticketId:
                  type: integer
                  example: 4
                message:
                  type: string
                  example: 'Dear student ABC...'
      operationId: ticketM2
      responses:
        '201':
          description: sample success response - return ticket marked duplicate
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Resolved
                    replies: 
                      - { userId : 10,
                       message: 'Dear student ABC...'
                      }
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: 5
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
  /faq:
    description: operations related to faqs
    post:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: create a new faq (staff only)
      operationId: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                staffId:
                  type: integer
                  example: 4
                ticketId:
                  type: integer
                  example: 12
      responses:
        '201':
          description: return newly created faq
          content:
            application/json:
              examples:
                201 result:
                  value:
                    faqId: 1
                    title: >-
                      Does IIT Madras offer B.Sc in Programming & Data Science
                      on-campus?
                    soltuion: >-
                      No, there is no equivalent on-campus version. IIT Madras
                      has carefully curated this exclusively as an online
                      program.
                    categories:
                      - General
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
    get:
      tags:
        - faq
      summary: ''
      description: get all available faqs
      operationId: ''
      responses:
        '200':
          description: returns list of all faqs
          content:
            application/json:
              examples:
                200 result:
                  value:
                    faqs:
                      - faqId: 1
                        title: >-
                          Does IIT Madras offer B.Sc in Programming & Data
                          Science on-campus?
                        solution: >-
                          No, there is no equivalent on-campus version. IIT
                          Madras has carefully curated this exclusively as an
                          online program.
                        categories:
                          - General
                      - faqId: 23
                        title: >-
                          I ran into an error or issue in the application form. What do I do?
                        solution: >-
                          Please send us your registered email ID and a screenshot of the error / issue with relevant description to support@onlinedegeree.iitm.ac.in
                          If the error is after payment has been made, please forward the confirmation email from Razorpay along with email ID, application number and screenshot with description.
                        categories:
                          - Application
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
  /faq/{faqId}:
    description: operations related to a particular faq
    parameters:
      - name: faqId
        description: id of faq
        required: true
        in: path
        schema:
          type: integer
          example: 4
    put:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: update a particular faq
      operationId: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newTitle:
                  type: string
                  example: "Does IITM offer B.S in Programming and Data Science on-campus?"
                newSolution:
                  type: string
                  example: "No, IITM does not offer this degree on-campus. This is exclusively online."
                newTags:
                  type: array
                  items:
                    type: string
                  example: [General, Campus]
      responses:
        '200':
          description: return updated faq
          content:
            application/json:
              examples:
                200 result:
                  value:
                    faqId: 4
                    title: >-
                      Does IITM offer B.S in Programming and Data Science on-campus?
                    soltuion: >-
                      No, IITM does not offer this degree on-campus. This is exclusively online.
                    categories:
                      - General
                      - Campus
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
    delete:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: delete a particular faq
      operationId: ''
      responses:
        '200':
          description: deleted successfully
          content:
            application/json:
              examples:
                200 result:
                  value:
                    status: true
                    message: faq deleted successfully
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error